package res.input;

// Partially copied from heaps: https://github.com/HeapsIO/heaps/
enum abstract Key(Int) from Int to Int {
	inline var BACKSPACE = 8;
	inline var TAB = 9;
	inline var ENTER = #if java 10 #else 13 #end;
	inline var SHIFT = 16;
	inline var CTRL = 17;
	inline var ALT = 18;
	inline var ESCAPE = 27;
	inline var SPACE = 32;
	inline var PGUP = 33;
	inline var PGDOWN = 34;
	inline var END = 35;
	inline var HOME = 36;
	inline var LEFT = 37;
	inline var UP = 38;
	inline var RIGHT = 39;
	inline var DOWN = 40;
	inline var INSERT = 45;
	inline var DELETE = 46;
	inline var QWERTY_EQUALS = 187;
	inline var QWERTY_MINUS = 189;
	inline var QWERTY_TILDE = 192;
	inline var QWERTY_BRACKET_LEFT = 219;
	inline var QWERTY_BRACKET_RIGHT = 221;
	inline var QWERTY_SEMICOLON = 186;
	inline var QWERTY_QUOTE = 222;
	inline var QWERTY_BACKSLASH = 220;
	inline var QWERTY_COMMA = 188;
	inline var QWERTY_PERIOD = 190;
	inline var QWERTY_SLASH = 191;
	inline var INTL_BACKSLASH = 226; // Backslash located next to left shift on some keyboards. Warning: Not available on HLSDL.
	inline var LEFT_WINDOW_KEY = 91;
	inline var RIGHT_WINDOW_KEY = 92;
	inline var CONTEXT_MENU = 93;
	// inline var PRINT_SCREEN = // Only available on SDL
	inline var PAUSE_BREAK = 19;
	inline var CAPS_LOCK = 20;
	inline var NUM_LOCK = 144;
	inline var SCROLL_LOCK = 145;
	inline var NUMBER_0 = 48;
	inline var NUMBER_1 = 49;
	inline var NUMBER_2 = 50;
	inline var NUMBER_3 = 51;
	inline var NUMBER_4 = 52;
	inline var NUMBER_5 = 53;
	inline var NUMBER_6 = 54;
	inline var NUMBER_7 = 55;
	inline var NUMBER_8 = 56;
	inline var NUMBER_9 = 57;
	inline var NUMPAD_0 = 96;
	inline var NUMPAD_1 = 97;
	inline var NUMPAD_2 = 98;
	inline var NUMPAD_3 = 99;
	inline var NUMPAD_4 = 100;
	inline var NUMPAD_5 = 101;
	inline var NUMPAD_6 = 102;
	inline var NUMPAD_7 = 103;
	inline var NUMPAD_8 = 104;
	inline var NUMPAD_9 = 105;
	inline var A = 65;
	inline var B = 66;
	inline var C = 67;
	inline var D = 68;
	inline var E = 69;
	inline var F = 70;
	inline var G = 71;
	inline var H = 72;
	inline var I = 73;
	inline var J = 74;
	inline var K = 75;
	inline var L = 76;
	inline var M = 77;
	inline var N = 78;
	inline var O = 79;
	inline var P = 80;
	inline var Q = 81;
	inline var R = 82;
	inline var S = 83;
	inline var T = 84;
	inline var U = 85;
	inline var V = 86;
	inline var W = 87;
	inline var X = 88;
	inline var Y = 89;
	inline var Z = 90;
	inline var F1 = 112;
	inline var F2 = 113;
	inline var F3 = 114;
	inline var F4 = 115;
	inline var F5 = 116;
	inline var F6 = 117;
	inline var F7 = 118;
	inline var F8 = 119;
	inline var F9 = 120;
	inline var F10 = 121;
	inline var F11 = 122;
	inline var F12 = 123;
	// Extended F keys
	inline var F13 = 124;
	inline var F14 = 125;
	inline var F15 = 126;
	inline var F16 = 127;
	inline var F17 = 128;
	inline var F18 = 129;
	inline var F19 = 130;
	inline var F20 = 131;
	inline var F21 = 132;
	inline var F22 = 133;
	inline var F23 = 134;
	inline var F24 = 135;
	inline var NUMPAD_MULT = 106;
	inline var NUMPAD_ADD = 107;
	inline var NUMPAD_ENTER = 108;
	inline var NUMPAD_SUB = 109;
	inline var NUMPAD_DOT = 110;
	inline var NUMPAD_DIV = 111;
	inline var MOUSE_LEFT = 0;
	inline var MOUSE_RIGHT = 1;
	inline var MOUSE_MIDDLE = 2;
	inline var MOUSE_BACK = 3;
	inline var MOUSE_FORWARD = 4;

	/** a bit that is set for left keys **/
	inline var LOC_LEFT = 256;

	/** a bit that is set for right keys **/
	inline var LOC_RIGHT = 512;

	inline var LSHIFT = SHIFT | LOC_LEFT;
	inline var RSHIFT = SHIFT | LOC_RIGHT;
	inline var LCTRL = CTRL | LOC_LEFT;
	inline var RCTRL = CTRL | LOC_RIGHT;
	inline var LALT = ALT | LOC_LEFT;
	inline var RALT = ALT | LOC_RIGHT;
}

final KeyNames:Map<Key, String> = [
	BACKSPACE => 'BACKSPACE',
	TAB => 'TAB',
	ENTER => 'ENTER',
	SHIFT => 'SHIFT',
	CTRL => 'CTRL',
	ALT => 'ALT',
	ESCAPE => 'ESCAPE',
	SPACE => 'SPACE',
	PGUP => 'PGUP',
	PGDOWN => 'PGDOWN',
	END => 'END',
	HOME => 'HOME',
	LEFT => 'LEFT',
	UP => 'UP',
	RIGHT => 'RIGHT',
	DOWN => 'DOWN',
	INSERT => 'INSERT',
	DELETE => 'DELETE',
	QWERTY_EQUALS => 'QWERTY_EQUALS',
	QWERTY_MINUS => 'QWERTY_MINUS',
	QWERTY_TILDE => 'QWERTY_TILDE',
	QWERTY_BRACKET_LEFT => 'QWERTY_BRACKET_LEFT',
	QWERTY_BRACKET_RIGHT => 'QWERTY_BRACKET_RIGHT',
	QWERTY_SEMICOLON => 'QWERTY_SEMICOLON',
	QWERTY_QUOTE => 'QWERTY_QUOTE',
	QWERTY_BACKSLASH => 'QWERTY_BACKSLASH',
	QWERTY_COMMA => 'QWERTY_COMMA',
	QWERTY_PERIOD => 'QWERTY_PERIOD',
	QWERTY_SLASH => 'QWERTY_SLASH',
	INTL_BACKSLASH => 'INTL_BACKSLASH',
	LEFT_WINDOW_KEY => 'LEFT_WINDOW_KEY',
	RIGHT_WINDOW_KEY => 'RIGHT_WINDOW_KEY',
	CONTEXT_MENU => 'CONTEXT_MENU',
	PAUSE_BREAK => 'PAUSE_BREAK',
	CAPS_LOCK => 'CAPS_LOCK',
	NUM_LOCK => 'NUM_LOCK',
	SCROLL_LOCK => 'SCROLL_LOCK',
	NUMBER_0 => 'NUMBER_0',
	NUMBER_1 => 'NUMBER_1',
	NUMBER_2 => 'NUMBER_2',
	NUMBER_3 => 'NUMBER_3',
	NUMBER_4 => 'NUMBER_4',
	NUMBER_5 => 'NUMBER_5',
	NUMBER_6 => 'NUMBER_6',
	NUMBER_7 => 'NUMBER_7',
	NUMBER_8 => 'NUMBER_8',
	NUMBER_9 => 'NUMBER_9',
	NUMPAD_0 => 'NUMPAD_0',
	NUMPAD_1 => 'NUMPAD_1',
	NUMPAD_2 => 'NUMPAD_2',
	NUMPAD_3 => 'NUMPAD_3',
	NUMPAD_4 => 'NUMPAD_4',
	NUMPAD_5 => 'NUMPAD_5',
	NUMPAD_6 => 'NUMPAD_6',
	NUMPAD_7 => 'NUMPAD_7',
	NUMPAD_8 => 'NUMPAD_8',
	NUMPAD_9 => 'NUMPAD_9',
	A => 'A',
	B => 'B',
	C => 'C',
	D => 'D',
	E => 'E',
	F => 'F',
	G => 'G',
	H => 'H',
	I => 'I',
	J => 'J',
	K => 'K',
	L => 'L',
	M => 'M',
	N => 'N',
	O => 'O',
	P => 'P',
	Q => 'Q',
	R => 'R',
	S => 'S',
	T => 'T',
	U => 'U',
	V => 'V',
	W => 'W',
	X => 'X',
	Y => 'Y',
	Z => 'Z',
	F1 => 'F1',
	F2 => 'F2',
	F3 => 'F3',
	F4 => 'F4',
	F5 => 'F5',
	F6 => 'F6',
	F7 => 'F7',
	F8 => 'F8',
	F9 => 'F9',
	F10 => 'F10',
	F11 => 'F11',
	F12 => 'F12',
	F13 => 'F13',
	F14 => 'F14',
	F15 => 'F15',
	F16 => 'F16',
	F17 => 'F17',
	F18 => 'F18',
	F19 => 'F19',
	F20 => 'F20',
	F21 => 'F21',
	F22 => 'F22',
	F23 => 'F23',
	F24 => 'F24',
	NUMPAD_MULT => 'NUMPAD_MULT',
	NUMPAD_ADD => 'NUMPAD_ADD',
	NUMPAD_ENTER => 'NUMPAD_ENTER',
	NUMPAD_SUB => 'NUMPAD_SUB',
	NUMPAD_DOT => 'NUMPAD_DOT',
	NUMPAD_DIV => 'NUMPAD_DIV',
	MOUSE_LEFT => 'MOUSE_LEFT',
	MOUSE_RIGHT => 'MOUSE_RIGHT',
	MOUSE_MIDDLE => 'MOUSE_MIDDLE',
	MOUSE_BACK => 'MOUSE_BACK',
	MOUSE_FORWARD => 'MOUSE_FORWARD',
	LOC_LEFT => 'LOC_LEFT',
	LOC_RIGHT => 'LOC_RIGHT',
	SHIFT | LOC_LEFT => 'LSHIFT',
	SHIFT | LOC_RIGHT => 'RSHIFT',
	CTRL | LOC_LEFT => 'LCTRL',
	CTRL | LOC_RIGHT => 'RCTRL',
	ALT | LOC_LEFT => 'LALT',
	ALT | LOC_RIGHT => 'RALT'
];
